name: Deploy project and perform DAST

on:
  push:
    branches: ["main"]          

jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    env:
      IMAGE_NAME: ghcr.io/carlospagan/devops
  
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Images
        run: docker build -t $IMAGE_NAME:${GITHUB_SHA::7} -t $IMAGE_NAME:latest .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Push SHA
        run: docker push $IMAGE_NAME:${GITHUB_SHA::7}

      - name: Docker Push Latest
        run: docker push $IMAGE_NAME:latest

  ngrok-tunnel:
      name: Docker container with Ngrok tunnel
      runs-on: ubuntu-latest
      needs: deploy
  
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run container
        run: docker run -e NGROK_AUTHTOKEN=${{ secrets.NGROK_AUTHTOKEN}} ngrok/ngrok http 80 --domain=free-direct-walrus.ngrok-free.app

  zap_scan:
    runs-on: ubuntu-latest
    needs: ngrok-tunnel
    steps:
      - name: Scan the webapplication
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'http://free-direct-walrus.ngrok-free.app'


