name: Deploy project and perform DAST

on:
  push:
    branches: ["main"]          

jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    env:
      IMAGE_NAME: ghcr.io/carlospagan/devops
  
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Images
        run: docker build -t $IMAGE_NAME:${GITHUB_SHA::7} -t $IMAGE_NAME:latest .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Push SHA
        run: docker push $IMAGE_NAME:${GITHUB_SHA::7}

      - name: Docker Push Latest
        run: docker push $IMAGE_NAME:latest
   
  run-application:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      packages: "read"
    env:
      IMAGE_NAME: ghcr.io/carlospagan/devops
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
       
      - name: Install Ngrok
        run: curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo gpg --dearmor -o /etc/apt/keyrings/ngrok.gpg && echo "deb [signed-by=/etc/apt/keyrings/ngrok.gpg] https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
      
      - name: Setup Token
        run: ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}

      - name: Run the webapplication
        run: docker run -d -p 80:80 ghcr.io/carlospagan/devops:latest
        
      - name: Expose the webapplication
        run: ngrok http 80 --domain=free-direct-walrus.ngrok-free.app

  zap_scan:
    runs-on: ubuntu-latest
    needs: run-application
    steps:
      - name: Scan the webapplication
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'http://free-direct-walrus.ngrok-free.app'


